[package]
name = "gpl-gateway"
version = "0.1.1"
description = "SPL Governance addin gateway"
license = "Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "gpl_gateway"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
arrayref = "0.3.6"
anchor-lang = { version = "0.24.2", features = ["init-if-needed"] }
anchor-spl = "0.24.2"
itertools = "0.10.2"
solana-gateway = "0.2.2"
solana-program = "1.9.13"
spl-governance = { version = "2.2.4", features = ["no-entrypoint"] }
spl-governance-tools=  "0.1.2"
spl-governance-addin-api = "0.1.2"
spl-token = { version = "3.3", features = [ "no-entrypoint" ] }

[dev-dependencies]
borsh = "0.9.1"
solana-sdk = "1.9.5"
solana-program-test = "1.9.13"
spl-governance-addin-mock = "0.1.2"